export type InvidiousEntityType = "video" | "shortVideo" | "channel" | "playlist" | "invidiousPlaylist" | "hashtag" | string;

export interface ImageObject {
  url: string;
  width: number;
  height: number;
}

export interface ThumbnailObject {
  quality: string;
  url: string;
  width: number;
  height: number;
}

export interface VideoObject {
  type: "video" | "shortVideo" | string;
  title: string;
  videoId: string;
  author: string;
  authorId: string;
  authorUrl: string;
  authorVerified?: boolean;
  videoThumbnails: ThumbnailObject[];
  authorThumbnails?: ThumbnailObject[];
  description?: string;
  descriptionHtml?: string;
  viewCount?: number;
  viewCountText?: string;
  lengthSeconds?: number;
  published?: number;
  publishedText?: string;
  premiereTimestamp?: number;
  liveNow?: boolean;
  premium?: boolean;
  paid?: boolean;
  isUpcoming?: boolean;
  isNew?: boolean;
  is4k?: boolean;
  is8k?: boolean;
  isVr180?: boolean;
  isVr360?: boolean;
  is3d?: boolean;
  hasCaptions?: boolean;
  playlistId?: string;
  playlistThumbnail?: string;
}

export interface ChannelObject {
  type: "channel";
  author: string;
  authorId: string;
  authorUrl: string;
  authorVerified?: boolean;
  authorThumbnails: ThumbnailObject[];
  autoGenerated?: boolean;
  subCount?: number;
  videoCount?: number;
  description?: string;
  descriptionHtml?: string;
}

export interface PlaylistVideoObject {
  title: string;
  videoId: string;
  author?: string;
  authorId?: string;
  authorUrl?: string;
  lengthSeconds?: number;
  index?: number;
  indexId?: string;
  videoThumbnails: ThumbnailObject[];
}

export interface PlaylistObject {
  type: "playlist" | "invidiousPlaylist";
  title: string;
  playlistId: string;
  playlistThumbnail?: string;
  author: string;
  authorId?: string | null;
  authorUrl?: string | null;
  authorVerified?: boolean;
  videoCount?: number;
  videos?: PlaylistVideoObject[];
}

export interface AdaptiveFormat {
  index?: string;
  bitrate?: string;
  init?: string;
  url: string;
  itag?: string;
  type?: string;
  clen?: string;
  lmt?: string;
  projectionType?: string;
  fps?: number;
  container?: string;
  encoding?: string;
  qualityLabel?: string;
  resolution?: string;
}

export interface FormatStream {
  url: string;
  itag?: string;
  type?: string;
  quality?: string;
  bitrate?: string;
  container?: string;
  encoding?: string;
  qualityLabel?: string;
  resolution?: string;
  size?: string;
}

export interface Caption {
  label?: string;
  languageCode?: string;
  url?: string;
}

export interface MusicTrack {
  song?: string;
  album?: string;
  artist?: string;
  license?: string;
}

export interface RecommendedVideo extends VideoObject {
  recommended?: boolean;
}

export interface VideoDetails extends VideoObject {
  hlsUrl?: string;
  dashUrl?: string;
  adaptiveFormats: AdaptiveFormat[];
  formatStreams: FormatStream[];
  captions: Caption[];
  musicTracks: MusicTrack[];
  recommendedVideos: RecommendedVideo[];
  likeCount?: number;
  dislikeCount?: number;
  genre?: string;
  allowRatings?: boolean;
  subCount?: number;
  commentCount?: number;
}

export interface HashtagObject {
  type: "hashtag" | string;
  title?: string;
  hashtag?: string;
  hashtagUrl?: string;
  description?: string;
  descriptionHtml?: string;
}

export type SearchResultObject = VideoObject | ChannelObject | PlaylistObject | HashtagObject;

export interface CommentAuthorThumbnail {
  url: string;
  width: number;
  height: number;
}

export interface CommentObject {
  author: string;
  authorThumbnails: CommentAuthorThumbnail[];
  authorId?: string;
  authorUrl?: string;
  isEdited?: boolean;
  isPinned?: boolean;
  content: string;
  contentHtml?: string;
  published: number;
  publishedText?: string;
  likeCount?: number;
  commentId: string;
  authorIsChannelOwner?: boolean;
  creatorHeart?: boolean;
}

export interface CommentsResponse {
  commentCount?: number;
  videoId?: string;
  continuation?: string;
  comments: CommentObject[];
}

export interface ChannelDetails {
  author: string;
  authorId: string;
  authorUrl: string;
  authorBanners?: ImageObject[];
  authorThumbnails: ThumbnailObject[];
  subCount?: number;
  totalViews?: number;
  joined?: number;
  autoGenerated?: boolean;
  isFamilyFriendly?: boolean;
  description?: string;
  descriptionHtml?: string;
  latestVideos?: VideoObject[];
  relatedChannels?: ChannelObject[];
  tabs?: string[];
}

export interface ChannelVideosResponse {
  continuation?: string;
  videos: VideoObject[];
}

export interface ChannelPlaylistsResponse {
  continuation?: string;
  playlists: PlaylistObject[];
}

export interface InvidiousStats {
  software?: {
    name?: string;
    version?: string;
  };
  usage?: {
    users?: {
      total?: number;
      activeHalfyear?: number;
      activeMonth?: number;
    };
  };
  metadata?: {
    updatedAt?: number;
  };
}

export interface AuthFeedResponse {
  notifications?: number;
  videos?: VideoObject[];
}

export type AuthSubscriptionsResponse = ChannelObject[];

export type AuthPlaylistsResponse = PlaylistObject[];

export interface Preferences {
  dark_mode?: boolean;
  locale?: string;
  region?: string;
  [key: string]: unknown;
}
